name: "Build MacOS"
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Build
          #brew install gcc@14
        run: |
          make fasthenry
          ls bin
          zip fasthenry-macOS.zip -vj bin/fasthenry

      
      - name: Release to GitHub
        uses: softprops/action-gh-release@v3
        with:
          files: |
            fasthenry-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}